# Generated by Django 3.1.6 on 2021-02-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plandata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toki', models.DateField()),
                ('basho', models.CharField(max_length=100)),
                ('naiyo', models.CharField(max_length=200)),
            ],
        ),
    ]
