# Generated by Django 3.1.6 on 2021-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toki', models.DateField()),
                ('kanryo_day', models.DateField()),
                ('basho', models.CharField(max_length=100)),
                ('naiyo', models.CharField(max_length=200)),
            ],
        ),
    ]
