# Generated by Django 3.1.6 on 2021-03-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0002_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion',
            name='basho',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='completion',
            name='naiyo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='basho',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='naiyo',
            field=models.CharField(max_length=100),
        ),
    ]
